### ISSUE TITLE
A lot of feedback

### ISSUE THREAD

**Issue by Stono** [gocd/docker-gocd-server#13]
Hello GoCD team.
I have a lot of feedback and issues caused by your recent migration from v17.2 -> v17.3.

In your move to the new base images, you've fundamentally changed several things which are causing me a lot of pain:

1. The underlying OS of the image, subsequently any scripts i had written no longer work and require changing to support alpine.  Things like curl (which were there before) and now not.
2. The file/folder structure is incompatibly different, previously I was mount /var/lib/go-server and /etc/go as separate volumes, as they're now /godata and /godata/config, i have a situation where I cannot migrate from 17.2 to 17.3 as my persistent volumes can't be nested under each other.
3. You've removed the old images from docker hub (https://hub.docker.com/r/stono/gocd-server and https://hub.docker.com/r/gocd/gocd-agent/) which has subsequently broken my existing build pipelines.

I'm disappointed to find that these changes appear to have been made without consideration as to the impact of people who use your docker images 'not at face value', ie, people who inherit from them as I do.  These changes will now affect three product teams that I am aware of.

If we think about semantic versioning, 17.2 -> 17.3 would imply 'adding functionality in a backwards compatible manner', which these changes are not.   I would ask you to consider your docker images as part of your product release lifecycle, as such in making such large breaking changes, you should be bumping your major version and also giving the community sufficient notice as to the changes, in order to prepare them.  Docker images are just as much a part of your application code as the application code is, breaking changes in your Docker images affect your users just as much as breaking changes in your Java code.

Thanks

**Comment by Stono** [comment]
I know this is in your agent, but it's another example of a breaking change.
https://github.com/gocd/docker-gocd-agent-centos-7/blob/master/Dockerfile#L35

Adding that Volume line there means that anyone building FROM your docker container, and writing things to /home/go as part of their Dockerfile (for example; we write some gcloud, kubectl config there) will break, as those changes don't persist.

**Comment by varshavaradarajan** [comment]
@Stono ,
We moved from the phusion images to alpine because using the alpine base image made the server lighter (reduced the server image size by 500 MB or thereabouts) for downloads. Since, the go-server is just an orchestrator, we provided the simplest image with support for just java and the basic scms. The phusion image was based on ubuntu and hence brought in a bunch of other dependencies which bloated up the image. From a GoCD server image point of view, it did not make sense, hence the decision to switch to Alpine was made. There was a good amount of gocd/gocd-docker#27 that went into the reasoning behind this, may be going through those will give you some clarity about our perspective.
We understand that your scripts might be written in a way that it does not work with the newer image and hence we have left the old images around. They were moved to a different location though => https://hub.docker.com/r/gocd/gocd-server-deprecated and https://hub.docker.com/r/gocd/gocd-agent-deprecated. In order to get your builds running, you should just be able to point to those images instead. The phusion image for 17.3.0 is also available so you should be able to use the latest version as well. This is already mentioned in the 17.3 release notes.
I agree that there wasn't sufficient notice given, we take that as a feedback. We have mentioned about the agent images in the breaking changes too for 17.3, but the server image being broken in not in that section at the moment. We will add it. Thanks for pointing it out.

Also, do you mind telling why you were using curl on the server?

**Comment by varshavaradarajan** [comment]
> I know this is in your agent, but it's another example of a breaking change.
https://github.com/gocd/docker-gocd-agent-centos-7/blob/master/Dockerfile#L35

> Adding that Volume line there means that anyone building FROM your docker container, and writing things to /home/go as part of their Dockerfile (for example; we write some gcloud, kubectl config there) will break, as those changes don't persist.

Check https://github.com/gocd/docker-gocd-agent/issues/16 and https://github.com/gocd/docker-gocd-agent/pull/17.
The /home/go directory will still be created as part of useradd. Specifying it [here](https://github.com/gocd/docker-gocd-agent-centos-7/blob/master/Dockerfile#L35) meant the /home/go was owned by root. Anybody wishing to persist the config can use the `-v` option and access the configs you mentioned on the host.

**Comment by Stono** [comment]
@varshavaradarajan I was using curl in my custom boot script to download plugins at run time, onto a kubernetes persistent volume.  https://github.com/Stono/gocd-master/blob/master/scripts/run_go.sh

But the **what** I was doing, isn't really the point here.  The point I am trying to make here is that people may be using these files in ways in which you are not, and you will never pre-empt the impact of your changes for all of the different use cases.  For example in my particular use case I am running on kubernetes, certain files are mounted as kubernetes volumes, some are persistent volumes, others are run time configuration, others are built into the Dockerfile.

With regards to your agent comment, I understand why you have made your change, however that change breaks my workflow, as I build a generic container with some configuration written to the home directory in advance, which I never want to volume mount.

So going my back to my original point it is **extremely** important that you consider changes to your Dockerfiles is exactly the same way you would consider changes to your Java code, and honour semantic versioning.

**Comment by Stono** [comment]
@varshavaradarajan can you please point me to the github commits that triggered the builds of:

- https://hub.docker.com/r/gocd/gocd-server-deprecated/
- https://hub.docker.com/r/gocd/gocd-agent-deprecated/

I will then fork them and continue to maintain them separately none of the product teams I'm working with have the time right now in order to handle the migration to your new images.

**Comment by varshavaradarajan** [comment]
https://github.com/gocd/gocd-docker/tree/deprecated-docker-images

**Comment by varshavaradarajan** [comment]
@Stono , as part of https://github.com/gocd/docker-gocd-agent/pull/17, we have *removed* /home/go from the volume line. 

If you are extending our image in your dockerfile to write those configs to `/home/go` in advance, but those weren't persisted when you did a docker run because  of the VOLUME line. That's what I understood by it, is that right?  

Well, as part of the PR `/home/go` is removed, which should solve your problem, I think? And should users use our image directly, then can use the `-v` option during docker run to provide ssh keys and other secrets.

**Comment by Stono** [comment]
Closing this issue as I don't expect a resolution, I just wanted to give feedback.
I'm well aware of what you have done, and I'm aware of what I need to do in order to work with your new images.  The point is that I (nor the other teams) have time right now and subsequently we're going to be stuck on 17.3 indefinitely.

I would suggest the following moving forward to help engage the community better:

- Treating changes to Dockerfiles as you would do your application, in such that 'breaking' changes are only done as part of major version updates, and ample notice given
- Having a working group, or feedback group that can test and validate changes in advance, perhaps releasing the images first tagged with `-prerelease`, in the same way a lot of linux distros have a `testing` repository where people can pull upcoming releases and test.
- Doing some more user research to find out about how your community is using your Docker images, as part of A&D (You may already do this, I just haven't seen it), would help you ensure you're making changes that deliver significant value to the community

thanks!
Karl
